name: luthor_example
description: An example package for luthor
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  luthor: ^0.16.0 # Configured via catalog

dev_dependencies:
  lints: ^6.0.0
