name: _

environment:
  sdk: ">=3.8.0 <4.0.0"

workspace:
  - packages/luthor
  - packages/luthor/example
  - packages/luthor_generator
  - packages/luthor_generator/example

dependencies:
  analyzer: ^9.0.0 # Configured via catalog
  build: ^4.0.0 # Configured via catalog
  source_gen: ^4.0.0 # Configured via catalog
