name: luthor
description: |
  A Dart validation library inspired by https://zod.dev 
  with support for code generation.
version: 0.15.0
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor
homepage: https://luthor.ex3.dev
resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  meta: any

dev_dependencies:
  lint: ^2.8.0
  test: ^1.25.15
