name: luthor
description: |
  A Dart validation library inspired by https://zod.dev 
  with support for code generation.
version: 0.5.3
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor
homepage: https://luthor.netlify.app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: any

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.1
