name: luthor_generator
description: Generate luthor schemas with Freezed
version: 0.3.2
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor_generator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.3.0
  build: ^2.4.1
  collection: ^1.18.0
  json_annotation: ^4.8.1
  luthor_annotation: ^0.3.0
  source_gen: ^1.5.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.1
