name: luthor_generator
description: Generate luthor schemas
version: 0.15.0
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor_generator
homepage: https://luthor.ex3.dev
resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  analyzer: ^8.0.0 # Configured via catalog
  build: ^4.0.0 # Configured via catalog
  collection: ^1.18.0
  dart_mappable: ^4.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  luthor: ^0.15.0
  source_gen: ^4.0.0 # Configured via catalog

dev_dependencies:
  build_runner: ^2.4.0
  freezed: ^3.0.3
  json_serializable: ^6.7.0
  lint: ^2.3.0
  test: ^1.25.14
